version: "3.8"
services:
  postgres:
    image: "postgres:16"
    hostname: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - "./db/docker:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
