name: "Build Docker"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: workflow/nix-shell-action@v3
        with:
          flakes: nixpkgs#docker
          script: |
            # Runs hello from a local flake.nix
            nix build .#docker
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
            IMAGE_NAME=website-server
            # Uses docker from the nixpkgs registry (see https://raw.githubusercontent.com/NixOS/flake-registry/master/flake-registry.json)
            IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
            IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
            VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
            [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
            echo IMAGE_ID=$IMAGE_ID
            echo VERSION=$VERSION
            docker tag fscs-website:latest $IMAGE_ID:$VERSION
            docker push $IMAGE_ID:$VERSION

